#!/usr/bin/env ansible-playbook
---
- name: Requirements for OpenStack Kolla Deployment
  hosts: ampere
  any_errors_fatal: true
  tasks:

#  - name: Build kolla containers
#    command: 'kolla-build -b debian -t source'
#    when:

#      - inventory_hostname == "openstack1"

  - name: kolla-ansible multinode bootstrap prechecks
    script: files/images_to_local_registry.sh creates=~/console.txt
    when:
      - inventory_hostname == "openstack1"
